Feature/cypress test case heatmap
nidhisinghai/observability pull request #4
Opened 2022-05-31 15:24 UTC by nidhisinghai

### Description
cypress test case for heatmap Chart Styles

### Check List
- [ ] New functionality includes testing.
- [ ] All tests pass
- [ ]  Added cypress test case for Heatmap render including Newly added feature of 'Chart Style'

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

@abasatwar @spattnaik

2022-06-01 10:02 UTC, abasatwar requested changes

2022-06-01 11:17 UTC, nidhisinghai commented on dashboards-observability/.cypress/integration/1_event_analytics.spec.js
> +    cy.get('stop[stop-color="rgb(5, 10, 172)"]').should('exist');
The Assert is different for each of the Test case so can't be combined but whatever is common line of code is moved to a beforeEach function.

2022-06-01 11:21 UTC, nidhisinghai commented on dashboards-observability/cypress.json
> +  "baseUrl": "http://localhost:5601/ryb",
No, i will remove this.

2022-06-01 11:21 UTC, nidhisinghai commented on dashboards-observability/cypress.json
> +    "opensearchDashboards": "localhost:5601/ryb",
No, i will remove this.

2022-06-02 09:29 UTC, abasatwar approved these changes

2022-09-15 08:03 UTC, nidhisinghai commented
new separate files are created for charts under visualizationcharts folder

2022-09-15 08:03 UTC, closed without merging